name: Continuous integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v5
      - name: ⚡ Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo
      - name: Install Rust targets
        run: rustup target add thumbv8m.main-none-eabihf thumbv7em-none-eabi thumbv6m-none-eabi
      - name: Run check
        run: cargo check
      - name: Run tests
        run: cargo test --workspace --all-targets
